version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/latest/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started
      - docker build -t my-app .

  post_build:
    commands:
      - echo Build completed
